### ISSUE TITLE
error in russian PDF acronym description

### ISSUE THREAD

**Issue by j123123** [dennis714/RE-for-beginners#119]
page 926 https://beginners.re/RE4B-RU.pdf ![screenshot](https://i.imgur.com/pX24c07.png)
https://github.com/dennis714/RE-for-beginners/blob/76bfaae7ce4543c49f7f9f8c491ab9b15c1cd8f2/acronyms.tex#L128

**Comment by dennis714** [comment]
Thanks! Fixed: https://github.com/dennis714/RE-for-beginners/commit/47dc392124ec0c65f495a32ea9b0e793c2cef941
