### ISSUE TITLE
MIPS conditional jumps inverted condition

### ISSUE THREAD

**Issue by 73696e65** [dennis714/RE-for-beginners#122]
Hello and thanks for your awesome book!

In `Listing 1.133: Optimizing GCC 4.4.5 (IDA)`, file `patterns/07_jcc/minmax/minmax_MIPS_O3_IDA_EN.lst` you have:

```
my_max:
; set $v1 to 1 if $a1<$a0:
                slt     $v1, $a1, $a0
; jump, if $a1<$a0:
                beqz    $v1, locret_10
```

If I am not wrong, the jump commentary is incorrect and instead it should be something like:
```
; jump if the condition $a1<$a0 is not true:
```

**Comment by dennis714** [comment]
Thanks, fixed: https://github.com/dennis714/RE-for-beginners/commit/3bfe04ba68d595b34632476eb0adf1a949a57d47
