### ISSUE TITLE
corrections

### ISSUE THREAD

**Issue by 73696e65** [dennis714/RE-for-beginners#124]
Hey again, if you do not mind to check if I am wrong:

- page 262:
`We see that the AX register contains 0x100 : the C0 flag is at the 16th bit.`
should be: `the C0 flag is at the 8th bit`

- page 277:
```
loc_8048448:
; store _a to ST(0), pop value at top of stack, leave _a at top
fstp st(1)
```
should be:
```
; store _a to ST(1), pop value at top of stack, leave _a at top
fstp st(1)
```

- page 281:
`VMOVGT.F64      D16, D17 ; copy "b" to D16` should be:
`VMOVGT.F64      D16, D17 ; copy "a" to D16` and later
```
If it gets executed, the value of b is to be written into D16 (that is currently stored in in D17 ). Otherwise the value of a stays in the D16 register.
```
should be:
```
If it gets executed, the value of *a* is to be written into D16 ... the value of *b* stays in the D16 register.
```

**Comment by dennis714** [comment]
Thanks!
Fixed: https://github.com/dennis714/RE-for-beginners/commit/e18eb770a0a1952ad1ca816286a37b138e62abbe

How to credit you properly in "thanks" section? Not sure about your full name.

**Comment by 73696e65** [comment]
Thank you, my full name is Norbert Szetei.

I am also not sure about the page 318 in PDF, why you mentioned that `The LDR.W R9, [R9] instruction works like LEA ( .1.6 on page 1001)`? `LDR.W` loads the memory word at the address pointed by `r9`, however `LEA` only computes this address.

**Comment by dennis714** [comment]
Yes, you're right: https://github.com/dennis714/RE-for-beginners/commit/4c89aa2136ce5e8d5b9861514d7b7dfb480d4a71

**Comment by 73696e65** [comment]
- page 336 - 1.20.4 Setting and clearing specific bits: FPU example
The image with the floating number seems to be broken (same problem as in p.393).

- page 354 - Listing 1.292: Non-optimizing GCC (Linaro) 4.8
In ASM listing, you have `X1 = 1<<1` instead of `X1 = 1<<i`.

- page 363
The LW instruction at address 0x10 sums up the high and low parts and loads the value of the rand_state variable into $V1.
.. There should be `$V0` instead of `$V1`. 

- page 368 - 1.22.2 Let’s allocate space for a structure using malloc()
Let's compile it now with optimization /0x, so it would be easy see what we need.
.. easy *to* see what

- page 386
Structure fields come in registers $A0..$A3 and then get reshuffled into $A1..$A4 for printf().
There is no $A4 and to pass the last argument, stack is used: 
`sw $a3, 0x28+var_18($sp)`

- page 393 - Handling float data type as a structure
see p.336

- page 395, Listing 1.350:
```
or      eax, 80000000h  ; set minus sign
mov     edx, eax
and     eax, 807FFFFFh  ; leave only significand and exponent in EAX
shr     edx, 23         ; prepare exponent
```
With `and eax, 807FFFFFh == and eax, 0b10000000011111111111111111111111` we leave only significand and sign in eax, but not the exponent.

- page 405
`Let's use a slightly modified example which was found [here]` - the URL which points to [here](http://cplus.about.com/od/learningc/ss/pointers2.htm#step8) is already unavailable

- page 428
```
loc_7F: ; CODE XREF: f(int,int *,int *,int *)+65
mov     edi, eax ; edi = ar1
and     edi, 0Fh ; is ar1 16-byte aligned?
jz      short loc_9A ; yes
test    edi, 3
```
Here `eax` contains address of `ar3`, which is assigned with `mov eax, [esp+10h+ar3]` shortly after the function begins. So instead of `ar1`, we are checking `ar3`.

- page 461 - 1.30.3 Loading a constant into a register
Aa we already know, all instructions have a length of 4 bytes in ARM mode ...
.. *As we already know

**Comment by dennis714** [comment]
Thanks, everything is fixed: https://github.com/dennis714/RE-for-beginners/commit/b13860e2fc3eb147cfa53b494282df628cfd6428

**Comment by dennis714** [comment]
BTW.
Bitcoins for bugs. Donald Knuth pays $2.56 to those who found error in his book(s). Obviously, I'm not him, but can also try to reward bughunters with bitcoins. Starting at 18-Nov-2016, I'll pay 0.002 BTC (ot 2 mBTC) for each bug found in the book. 
If you want, I can send you them.

**Comment by 73696e65** [comment]
Thank you very much, but I don't want them. Your book is free and I think it's the best introduction to RE which I ever read. So it's the least I can do.

- page 475
Subtraction of 0x20 is the same as ANDing value with 0x20 (0x....FFDF), but if this bit is set before:
.. the minus sign is missing: `with -0x20`

- page 483
The strstr() C/C++ standard library function is used to find and occurrence in a string.
should be `any occurrence in a string`

- page 504
In the section with `3.7.1 Three iterators` you commented `RDX=a1, RCX=a2`. That should be `RDX=a2, RCX=a1`.

- page 508
The last sentence before `3.8 Duff’s device`: `when the compiler was tested, is passed the tests.`
.. should be `it passed the tests.`

- page 530
`Listing 3.55: memcmp() example` uses `memcpy_1235` and `memcpy` instead of `memcmp_1235` and `memcmp`

**Comment by dennis714** [comment]
Thanks again! https://github.com/dennis714/RE-for-beginners/commit/40a8b9475977ff1632c3144f54d065858c7a320b
