### ISSUE TITLE
opcode wrong usage

### ISSUE THREAD

**Issue by loafbit** [dennis714/RE-for-beginners#126]
In this file: intro_CPU_ISA_EN.tex. The last sentence: There are, by the way, many other \ac{RISC} \ac{ISA}s with fixed length 32-bit opcodes, such as MIPS, PowerPC and Alpha AXP.  I think you r meaning is fixed length 32-bit instruction, an instruction includes an opcode that specifies the operation to perform, and MIPS use 6-bit opcode. And there are serval similar wrong usage in A couple of words about different ISAs paragraph.

**Comment by dennis714** [comment]
Yes, you're right! https://github.com/dennis714/RE-for-beginners/commit/d074d0944542f49eb94c0de2ceb9c70d6b03f686
