### ISSUE TITLE
duplicate in "patterns/03_printf/x86/x64.tex"

### ISSUE THREAD

**Issue by endless-love** [dennis714/RE-for-beginners#127]
**`\EN{\input{patterns/03_printf/x86/x64_EN}}`**
`\RU{\input{patterns/03_printf/x86/x64_RU}}`
`\PTBR{\input{patterns/03_printf/x86/x64_PTBR}}`
**`\EN{\input{patterns/03_printf/x86/x64_EN}}`**

There is two lines for English version here, which results in two "x64: 8 arguments" sub-sections in the PDF file.

Sorry for my bad English.

**Comment by dennis714** [comment]
Thanks, fixed: https://github.com/dennis714/RE-for-beginners/commit/2349d2051df090fbfb3c533c00183c4b1364252b
