### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by endless-love** [dennis714/RE-for-beginners#128]
In `patterns/04_scanf/1_simple/x86_EN.tex`, on [line 45](https://github.com/dennis714/RE-for-beginners/blob/master/patterns/04_scanf/1_simple/x86_EN.tex#L45): `EBP & saved value of \EBP \\`
If I am not wrong, it should be `EBP & saved value of \ESP \\`.

**Comment by dennis714** [comment]
No, it's correct, if the function started with PUSH EBP / MOV EBP, ESP.

**Comment by endless-love** [comment]
Ahh sorry, I misunderstood. Thank you.
