### ISSUE TITLE
Precision proposal in "Numeral systems"

### ISSUE THREAD

**Issue by mremy** [dennis714/RE-for-beginners#155]
At this line:
https://github.com/dennis714/RE-for-beginners/blob/master/patterns/numeral_EN.tex#L7
Maybe it could help to add something like:
10 in binary is 2 in decimal and is (should be ?) pronounced (thinked as ?) "one zero", not "ten";
Same for 100 or one tine is enough?
What do you think ?

**Comment by dennis714** [comment]
What about this? https://github.com/dennis714/RE-for-beginners/commit/c36dbed4f2901af94309bad51a5d25209b66e6b5

**Comment by mremy** [comment]
It's a good idea to separate it from an example, it's generic and clear.
+1
