### ISSUE TITLE
Compile fails

### ISSUE THREAD

**Issue by DSiekmeier** [dennis714/RE-for-beginners#165]
Is do not know why, but for me compiling fails with `make DE` with following message:

> ) (./afterword.tex (./afterword_DE.tex [104] [105])
> ! Undefined control sequence.
> l.8 \CN
>        {\input{afterword_CN}}

Greetings Dennis

**Comment by daveti** [comment]
I am pretty sure it is caused by the premature afterword_CN.tex, which I have just commented out in afterword.tex. Pull request is sent already.

Thanks,
Dave

**Comment by dennis714** [comment]
Fixed: https://github.com/dennis714/RE-for-beginners/commit/b697e72038a129f6121bc083e5bd2797b1d67aca
