### ISSUE TITLE
Missing spaces in `String patching` with radare

### ISSUE THREAD

**Issue by kdarkhan** [dennis714/RE-for-beginners#215]
In the English version of pdf from January 20th, in `Hello world: String patching` there are two missing spaces after words `rada.re` which you can see from the screenshot below.
I saw that the tex file contains the spaces correctly, so it is probably a latex quirk.

![screenshot from 2017-01-22 01-23-57](https://cloud.githubusercontent.com/assets/1087493/22177153/e94f28de-e042-11e6-9017-c374c55840da.png)

**Comment by dennis714** [comment]
Thanks, fixed: https://github.com/dennis714/RE-for-beginners/commit/d75daf6a793ee89caf1e37942f8ad252a58093c2
