### ISSUE TITLE
Translat[ors|tion] synchronization

### ISSUE THREAD

**Issue by mremy** [dennis714/RE-for-beginners#227]
Hello everyone,

I think we need something to:
P1  avoid to work on the same files, and waste time
P2 know wenn "source" (EN or RU) are modified by the author

Maybe it's 2 differents problems, with 2 solutions.
This "something" should be "KISS" (Keep It Simpole Stupid or something like this)

Ideas I had:
1) Have a kind of editable document with the list of files to be translated with "mutex", were translators add name/pseudo/whatever and date for holding the file. The date is to avoid holding a file for mounths, as they are small enough to be translated (guess) in 1/2 weeks. Are gist editable ?

2) Have a specific repo with commit right for everyone for translation (per language or one branch per language), but it seems overkill and adds a lot of work. On the over hand, it may be possible to add an hook from the RE4B repo adding changed file in EN/RU.

3) github "Projects" tab of this repo, but I never used them, has anyone used it ?

Just writing this is enough to see that they're effectively overkill, and hard to use.

4) P1: pushing an (almost) empty file before starting the translation may be enough, as a "git pull" before starting is okay. And it does not add to much noise in the repo history.
P2: A simple keyword (like CHANGED or TOCHECK) in the translated files may be enough, as it's easy to find.

5) hey dude, we don't need anything...

What do you think?

Marc

**Comment by mremy** [comment]
P1 closed by:
commit 275331eeadc367a5867a2aed6ac58b79ff5a57cf

**Comment by dennis714** [comment]
Yes, "mutex" idea is fine: https://github.com/dennis714/RE-for-beginners/blob/e85b151a977c74e78afa15fc4d9500c79cb68951/Translation.md#coordination

**Comment by mremy** [comment]
P2 has already a solution: \acro{TBT} !
