### ISSUE TITLE
Package xcolor Error: Undefined color `RED'.

### ISSUE THREAD

**Issue by mremy** [dennis714/RE-for-beginners#236]
I found the origin of this error.
It comes fom an \uppercase for text which is on the top of each page.
I made a small screen shot. 
![undefined_color_red_error](https://cloud.githubusercontent.com/assets/323967/22386666/73e708ce-e4d8-11e6-9896-813085d3f3a3.png)

I found 2 solutions, I don't know which one is the less uggly, so I didn't "pull request".
Both of them occurs in macros.tex
1) add the color definition for RED: 
+\definecolor{RED}{rgb}{1,0,0}
2) set the \LANGph macro to lowertext, example with French: 
-\newcommand{\FRph}{\FR{{\color{red}French text placeholder}}}
+\newcommand{\FRph}{\FR{{\lowercase{\color{red}}French text placeholder}}}

There's of course a third one:
3) Don't forget to translate any text... but it's hard to find the missing text.

**Comment by mremy** [comment]
After reading xcolor documentation, a more acceptable solution, is to not using the color name, but a definition:
-\newcommand{\FRph}{\FR{{\color{red}French text placeholder}}}
+\newcommand{\FRph}{\FR{{\color[rgb]{1,0,0}}French text placeholder}}
What a luck, xcolor seems to accept RGB as rgb :-)

**Comment by dennis714** [comment]
Maybe we can just translate all \FRph{}'s which happened to be in TOCs? :-)

**Comment by dennis714** [comment]
This is not a significant problem, anyway, "\definecolor{RED}..." hack is fine, IMHO.

But how did you get into this? I tried "make FR" right now, with no problems.

**Comment by mremy** [comment]
I agree that is not a signifiant problem. Don't waste time on it, I will (Idon't loke error, and, as usual, I think the solution is just around the corner) ;-)
It happened just before: https://github.com/dennis714/RE-for-beginners/pull/235
The purpose of this pull request, was to remove the FRph. Then, no more error.
I'll do some tests with the xcolor package.

**Comment by mremy** [comment]
This seems to work as expected:
\newcommand{\FRph}{\FR{{\color[RGB]{255,0,0}French text placeholder}}}

**Comment by mremy** [comment]
Translators, if you encounter this error, just grep for <YOUR_LANG>ph and translate the missing text.
The error will go away.
