### ISSUE TITLE
German translation not compilable

### ISSUE THREAD

**Issue by DSiekmeier** [dennis714/RE-for-beginners#237]
Hi there,
I get the following message when compiling with make DE. I am not very experienced with LaTex, but I wonder why does not catch one's eye when compiling on the local computer? Is it possible to improve the Travis CI check for theese kind of errors?

Kind Regards,
Dennis

> (./patterns/02_stack/stack_and_heap.tex [30])
> (./patterns/02_stack/01_saving_ret_addr.tex
> (./patterns/02_stack/01_saving_ret_addr_DE.tex
> Underfull \hbox (badness 10000) in paragraph at lines 3--4
> 
> 
> Overfull \hbox (44.13516pt too wide) in paragraph at lines 15--17
> [][][][][][][] \EU1/DejaVuSans(0)/m/n/10 ruft die Rückkehr Adresse vom Stack ab
>  und springt zu dieser ---was äquivalent zu einem [][][][][][]
> ! Undefined control sequence.
> <argument> \TBT 
>                 
> l.18 \myindex{\Stack!\MLStackOverflow}
>

**Comment by dennis714** [comment]
Thanks for your notice. That bug was caused by misspelling and appeared only if DE or ITA version would be compiled.
Fixed: https://github.com/dennis714/RE-for-beginners/commit/a0246743abbd548fd3fa247db159dad8f2c87ddb

**Comment by dennis714** [comment]
Travis CI now should catch bugs in DE and FR versions: https://github.com/dennis714/RE-for-beginners/commit/81311465b260c1a8c98b69b5cc01478ebbff70ce
