### ISSUE TITLE
Page 10 - Hello World Sample

### ISSUE THREAD

**Issue by tugrul** [dennis714/RE-for-beginners#248]
> Why 4? Since this is a 32-bit program, we need exactly 4 bytes for address passing through the stack.
If it was x64 code we would need 8 bytes. `ADD ESP, 4` is effectively equivalent to `POP register` but
without using any register.

Also needed to explanation why `ADD ESP, 4` why not `SUB ESP, 4`. If I remember correctly, stack pointer counting to reverse direction.

**Comment by dennis714** [comment]
This explained further.
