### ISSUE TITLE
Found litle diference-improvement on Chapter 1 - 1.9.3 Global Variables under Windows x86

### ISSUE THREAD

**Issue by nextco** [dennis714/RE-for-beginners#336]
# Found litle improvement on Chapter 1 - 1.9.3 Global Variables.
**Improvement:** Add a clarification on x86 versions _DATA is replaced by _BSS if variable x is not initialized [1].

Explanation:
I found diferences on asm code (produced by x86 compiler) for windows x86 on original book code [Source Code](https://raw.githubusercontent.com/nextco/RE4B/master/Chapter%201%20-%20Code%20Patterns/1.9.3-global-variables.cpp), [ASM Code](https://raw.githubusercontent.com/nextco/RE4B/master/Chapter%201%20-%20Code%20Patterns/1.9.3-global-variables.asm), **<- Lines 13-15** are not clear on the book, because it is citing the code with the initialized variable (showed asm code on the book).

The total updating of the asm code for 1.9.3 is not recommended, because _DATA is more didactic and easy to understand, and of course IDA show a .data section.

[1] [Source Code](https://github.com/nextco/RE4B/blob/master/Chapter%201%20-%20Code%20Patterns/1.9.3-global-variables-improvement.cpp), [ASM Code](https://github.com/nextco/RE4B/blob/master/Chapter%201%20-%20Code%20Patterns/1.9.3-global-variables-improvement.asm)

**Comment by dennis714** [comment]
Ah, the MSVC I used was too old... maybe 2008 or 2010. It can allocate uninitialized variable in _DATA segment, AFAIR.
