### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by malchugan** [dennis714/RE-for-beginners#45]
Hi,
First of all thanks for the lovely book and I hope I could contribute along the way.
I am new to LaTex and sorry if I am not very adequate in my descriptions. 
While trying to build the english version of the book I get the following error in:

./patterns/01_helloworld/GCC_x64.tex

*! Package Listings Error: File `patterns/01_helloworld/GCC_x64(.s.en)' not found.*

I guess it is because of the following reference 
{patterns/01_helloworld/GCC_x64.s.\LANG}

Kind Regards

**Comment by dennis714** [comment]
What OS do you use? I just checked in Linux...
https://github.com/dennis714/RE-for-beginners/blob/master/INSTALL

**Comment by malchugan** [comment]
Hi Dennis,
It is my bad. I use Debian wheezy with Texmaker. I've just double checked - command line make works fine, but Texmaker misbehaves probably due to misconfigured quick build option I am using.
Anyhow thanks for your quick response and sorry about the inconvenience.

Kind Regards

**Comment by dennis714** [comment]
That's fine, feel free to comment about your experience. I never used Texmaker.
