### ISSUE TITLE
Typos : chapter 6 (en)

### ISSUE THREAD

**Issue by Saroupille** [dennis714/RE-for-beginners#59]
On the page 33 (beginning of the chapter 6) : 

- There is a semi-colon at the end of the main function (first snippet)
-  "be deduced by simply dividing X by 4" : dividing should be multiplying no ?

**Comment by dennis714** [comment]
* What's wrong with semicolon?

* Yes, dividing.

**Comment by Saroupille** [comment]
That's just unsual

**Comment by dennis714** [comment]
I can tell you that it's rather unusual to read comments like yours.

**Comment by Saroupille** [comment]
My bad, sorry. I should have checked before.
