### ISSUE TITLE
Typo in russian page #119 JBE => JB

### ISSUE THREAD

**Issue by ASnow** [dennis714/RE-for-beginners#74]
Опечатка в русской версии на 119 странице под листингом 12.2 дважды написано JBE. Должно быть JB/JBE
=======
There is typo in russian version on page 119 under GCC example: twice JBE macro. Should be JB/JBE

**Comment by dennis714** [comment]
Thanks! Fixed in https://github.com/dennis714/RE-for-beginners/commit/7f7209689b0732d335ea785582f6624055bf041a
