### ISSUE TITLE
RIP/EIP/IP указывает на исполняющуюся инструкцию?

### ISSUE THREAD

**Issue by xzo** [dennis714/RE-for-beginners#77]
В книге написано:
"Обычно всегда указывает на исполняющуюся инструкцию."

Но в справочнике Intel написано:
EIP (instruction pointer) register. The EIP register contains a 32-bit pointer to the next instruction to be
executed.

Так на какую инструкцию регистр указывает: на ту, которая исполняется сейчас, или на следующую?

**Comment by dennis714** [comment]
Спсб, пофиксил! https://github.com/dennis714/RE-for-beginners/commit/f33c444d3d524cb5d082e8c09a2629fcbee30cfd
