### ISSUE TITLE
epub version of book

### ISSUE THREAD

**Issue by voroojax** [dennis714/RE-for-beginners#81]
Epub version of book would be great for reading in gadgets.
please consider releasing epub version either.
great book by the way.

thanks

**Comment by dennis714** [comment]
Thanks.

Epub is a compressed set of HTML files.
It is possible to produce HTML files from LaTeX, but my book is heavily dependent on PDF quirks and other LaTeX hacks/crutches, so it would be hard to do so...

**Comment by dennis714** [comment]
You may try A5 PDF version on your gadget: http://beginners.re/Reverse_Engineering_for_Beginners-en-A5.pdf

**Comment by voroojax** [comment]
thanks for your quick answer.
I tried A5 pdf, but yet it needs zoom in/out and not so comfortable to read in small sized gadgets.

**Comment by SkyREgit** [comment]
@voroojax No need to zoom in/out in Google PDF reader.
