### ISSUE TITLE
False positive: disassembler (non-)error

### ISSUE THREAD

**Issue by dnet** [dennis714/RE-for-beginners#87]
In [lines 18-20 of the string trim example](https://github.com/dennis714/RE-for-beginners/blob/master/advanced/200_string_trim/MSVC2013_x64_Ox.asm.m4#L18-L20) the following remark is included:

````asm
; here is probably disassembler (or assembler printing routine) error,
; LEA RDX... should be here instead of LEA EDX...
lea edx, DWORD PTR [rax-1]
````

But since we're loading a `DWORD`, which is 32 bits, I think `EDX` is appropriate, so **the output of the disassembler is correct and the remark is a false positive**. It would be `RDX` if `DWORD` would be `QWORD` instead, isn't it?

**Comment by dennis714** [comment]
I tried to recompile it, and got different result. This is weird. Probably, I used MSVC 2013 with some other servicepack?
Nevertheless, here is fixed clarified version: https://github.com/dennis714/RE-for-beginners/commit/8592182acef490a2894d292ba1e21fa57d6a4c18
