### ISSUE TITLE
Typo, RU, 9.3.3. Оптимизирующий Keil 6/2013 (Режим Thumb)

### ISSUE THREAD

**Issue by SkyREgit** [dennis714/RE-for-beginners#96]
> .text:0000005E 48 43 MULS R0, R1
> .text:00000060 80 18 ADDS **_R0, R0_**, R2
> .text:00000062 70 47 BX LR

В режиме Thumb инструкция MLA недоступна, так что компилятору пришлось сгенерировать код, делающий обе опе-
рации по отдельности. Первая инструкция MULS умножает R0 на R1 , оставляя результат в **_R1_** . Вторая ( ADDS )
складывает результат и R2 , оставляя результат в R0

**Comment by dennis714** [comment]
Thanks, fixed: https://github.com/dennis714/RE-for-beginners/commit/efa44a2f600b57baf52cae4a19a62e25a5742d95
