### ISSUE TITLE
Incorrect language in RE4B-EN

### ISSUE THREAD

**Issue by Sinderella** [dennis714/RE-for-beginners#97]
I just noticed that the file here: http://beginners.re/RE4B-EN.pdf has rendred incorrectly.

Check the page 49 of the book (or 72 of the PDF), you'll see that they're not English.

**Comment by dennis714** [comment]
Yes, you're right. Fixed: https://github.com/dennis714/RE-for-beginners/commit/2f1e3b7008bb79496a3b349a561fd197af441c3c
